name: clean_arch_project
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http:
  provider:
  equatable:
  get:
  flutter_secure_storage:
  localstorage:
  carousel_slider:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  test:
  mockito: ^5.1.0
  faker:
  network_image_mock: ^2.0.1


flutter:


  uses-material-design: true


